APPLICATION = samr21xpro-rtt-demo
RIOTBASE ?= $(CURDIR)/../..
BOARD ?= samr21-xpro
USEMODULE += xtimer
USEMODULE += rtt_stdio
QUIET ?= 1

FEATURES_REQUIRED += periph_timer

include $(RIOTBASE)/Makefile.include
